import Layout from "@/components/Layout";
import VideoCard from "@/components/VideoCard";
import { Flex } from "@chakra-ui/react";
import Head from "next/head";
import Script from "next/script";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Splash X</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1 className="shadow-md-secondary mb-6 text-center text-5xl font-bold text-error drop-shadow-[3px_3px_3px_#dc2626]">
          Splash X
        </h1>
        <div className="flex h-screen flex-col bg-gradient-to-b from-gray-900 to-slate-800 text-white">
          <main>
            <section className="text-center">
              <Flex justify={"center"} align={"center"} flexWrap={"wrap"}>
                <VideoCard />
                <VideoCard />
                <VideoCard />
              </Flex>
            </section>
          </main>

          <footer className="border-t border-gray-800 px-8 py-12">
            <div className="px-8 text-center font-medium">
              <span>Made with ❤️ by Team SplashX</span>
            </div>
          </footer>
        </div>
      </Layout>
      <Script src="https://buttons.github.io/buttons.js" />
    </div>
  );
}
